[project]
org-name = "chanakal"
version = "0.5.4"
authors = ["Chanaka Lakmal"]
keywords = ["google tasks", "google", "gtasks", "tasks"]
repository = "https://github.com/ldclakmal/package-googletasks"
license = "Apache-2.0"
